  
services:
  mybrain-neo4j:
    image: neo4j:latest
    container_name: mybrain-neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ${DATA_PATH}:/data
    environment:
      - NEO4J_AUTH=neo4j/tester11  # Default username/password
    networks:
      - mybrain-bridge

  mybrain-server:
    build: .
    container_name: mybrain-server
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - NEO4J_SCHEMA_VERSION=METAFILENODE
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    depends_on:
      - mybrain-neo4j
    networks:
      - mybrain-bridge
networks:
  mybrain-bridge:
    driver: bridge
